# Apology templates for Apology-as-a-Service
# Each template uses {context} as a placeholder for what went wrong.

from enum import Enum


class Severity(str, Enum):
    TRIVIAL = "TRIVIAL"
    MINOR = "MINOR"
    MAJOR = "MAJOR"
    CRITICAL = "CRITICAL"
    NUCLEAR = "NUCLEAR"


class Style(str, Enum):
    PROFESSIONAL = "PROFESSIONAL"
    CASUAL = "CASUAL"
    POETIC = "POETIC"
    GROVELING = "GROVELING"
    HAIKU = "HAIKU"
    LEGAL_DISCLAIMER = "LEGAL_DISCLAIMER"
    CORPORATE_DOUBLESPEAK = "CORPORATE_DOUBLESPEAK"
    SHAKESPEAREAN = "SHAKESPEAREAN"
    PIRATE = "PIRATE"


TEMPLATES = {
    Severity.TRIVIAL: {
        Style.PROFESSIONAL: [
            "Please accept my apologies for the minor oversight regarding {context}. It has been promptly corrected.",
            "I noticed a small discrepancy in {context} and have rectified it. Thank you for your patience.",
            "Regarding {context}, a minor adjustment was required and has been applied. We apologize for the notification.",
            "We have made a slight correction to {context} to ensure accuracy. No further action is required.",
            "A small administrative error was found in {context} and has since been resolved.",
            "Please note a minor revision to {context}. We apologize for any confusion.",
            "We have updated {context} to reflect the correct details. Thank you for your understanding.",
            "An insignificant error in {context} was caught and fixed. Operations continue as normal.",
        ],
        Style.CASUAL: [
            "My bad on the {context}. Fixed it!",
            "Oops, small typo in {context}. All good now.",
            "My brain glitched on {context} for a sec. Fixed.",
            "Note to self: Don't do {context} like that again. Sorted.",
            "Whoopsie, little hiccup with {context}. All smooth now.",
            "Just a quick fix for {context}. Carry on!",
            "Fixed that weird thing with {context}. My bad!",
            "Lol, sorry about {context}. I need more coffee. It's fixed.",
            "Minor fail on {context}. We're back in business.",
        ],
        Style.POETIC: [
            "A tiny speck of dust, a minor flaw, in {context} I did see and withdraw.",
            "Like a leaf in the wind, {context} fluttered astray, but has returned to the path.",
            "A ripple in the pond of {context}, now still once more.",
            "A momentary shadow passed over {context}, but the sun shines again.",
            "As a single false note in a symphony, {context} was briefly heard, then corrected.",
            "A fleeting cloud obscured {context}, but the sky is clear now.",
            "Like a typo in the book of life, {context} has been erased.",
            "A whisper of error in {context}, silenced by the truth.",
        ],
        Style.GROVELING: [
            "I am so sorry for the tiny mistake with {context}. I hope you can forgive this small trespass.",
            "I feel terrible about the slight imperfection in {context}. I hope it didn't bother you too much.",
            "Please don't be mad about the little thing in {context}. I fixed it immediately!",
            "I know it was small, but I am devastated that I let {context} happen. Sorry!",
            "I promise I usually pay more attention than I did with {context}. Please forgive me.",
            "I feel so silly for messing up {context}. I hope you don't think less of me.",
            "A thousand apologies for the microscopic issue with {context}.",
            "I am unworthy even of this trivial correction to {context}, but I offer it nonetheless.",
        ],
        Style.HAIKU: [
            "Small bug in code,\n{context} is fixed now,\nHappy day ahead.",
            "Tiny mistake made,\n{context} is perfect now,\nPeace returns to us.",
            "Oopsie daisy logic,\n{context} flows like water,\nAll is well again.",
            "A small typo found,\n{context} is right once more,\nAll is calm and bright.",
            "Briefly it was wrong,\n{context} sings a correct song,\nHarmony restored.",
            "Little glitch is gone,\n{context} stands strong and true,\nCoffee time for me.",
            "Shadow passes by,\n{context} shines in the light,\nDo not worry friend.",
            "One bit out of place,\n{context} back in its space,\nOrder is restored.",
        ],
        Style.LEGAL_DISCLAIMER: [
            "Without admitting fault or liability, we acknowledge that {context} required a de minimis adjustment.",
            "Notwithstanding the foregoing, a minor variance in {context} has been remediated. No further action is contemplated.",
            "Please be advised that {context} has undergone a non-material correction. This notice is informational only.",
            "Subject to the terms and conditions herein, {context} has been restored to its specified state.",
            "For the avoidance of doubt, the correction to {context} does not constitute a precedent.",
            "We hereby provide notice that {context} has been adjusted. All rights reserved.",
            "This communication regarding {context} is made without prejudice to any party.",
            "Per Section 3.2(b) of our SLA, the {context} variance falls below the materiality threshold.",
        ],
        Style.CORPORATE_DOUBLESPEAK: [
            "Opportunities for refinement were identified within {context} and have been operationalized.",
            "We have leveraged learnings from {context} to drive iterative excellence.",
            "{context} has been right-sized to align with our north-star outcomes.",
            "A minor optimization has been actioned against {context} to maximize stakeholder value.",
            "We have ideated and shipped a delta on {context} per our agile cadence.",
            "{context} was course-corrected as part of our continuous improvement loop.",
            "We circled back on {context} and unblocked the path to value.",
            "A low-impact recalibration was executed on {context} in service of our strategic flywheel.",
        ],
        Style.SHAKESPEAREAN: [
            "Forsooth, a most trifling error in {context} hath been mended by mine own hand.",
            "Pray, good sir, take no offense at the small slip in {context}, for 'tis now made whole.",
            "A mote of dust upon {context}, swept aside by gentle breath. Worry thee not.",
            "Mine humblest pardon for the wee misstep in {context}; the fault hath fled.",
            "Verily, {context} did stumble for a breath, then rose again most graceful.",
            "Be not vexed, dear friend, for {context} is restor'd unto its rightful form.",
            "A trifle, a nothing, a passing shadow upon {context}, now banished by the dawn.",
            "Mine apologies, most humbly tendered, for the slightest blemish upon {context}.",
        ],
        Style.PIRATE: [
            "Arrr, just a wee scratch on {context}, matey. All shipshape now!",
            "Avast! A bit o' barnacle on {context}, scraped clean she be.",
            "Yarr, {context} took a tiny sway in the wind. Steady as she goes now!",
            "Shiver me timbers, a small slip on {context}. Patched with grog and grit.",
            "Tiny squall over {context}, but the seas be calm again, ye scallywag.",
            "Arr, {context} had a wee leak. Plugged with me own beard, it be.",
            "By Blackbeard's ghost, {context} be sorted. Onwards to the booty!",
            "A pinch o' bother with {context}, but nothin' a parrot can't fix.",
        ],
    },
    Severity.MINOR: {
        Style.PROFESSIONAL: [
            "I apologize for the error in {context}. We have identified the cause and implemented a fix.",
            "We acknowledge the issue with {context}. Corrective measures have been taken to ensure standard operation.",
            "Please accept our apologies for the disruption in {context}. It has been resolved.",
            "We regret the inconvenience caused by the error in {context}. Steps have been taken to prevent a recurrence.",
            "An issue regarding {context} was brought to our attention and has been addressed.",
            "We have corrected the configuration regarding {context}. We apologize for the oversight.",
            "Please be advised that the issue with {context} has been mitigated.",
            "We apologize for the delay caused by {context}. We are back on schedule.",
        ],
        Style.CASUAL: [
            "Whoops, messed up {context} a bit. Sorting it out now.",
            "So, {context} didn't go exactly as planned. My bad. Fixing it.",
            "Yeah, {context} acted up. I gave it a stern talking to. It's behaving now.",
            "Glitch in the matrix regarding {context}. Rebooting common sense. Stand by.",
            "Okay, {context} was a bit of a mess. Cleaning it up!",
            "Sorry about the {context} drama. It's over now.",
            "My bad on {context}. I clicked the wrong thing. Classic me.",
            "Oops, {context} went sideways. Pushing it back upright.",
            "Hey, sorry about {context}. Gremlins in the system. Squashed 'em.",
        ],
        Style.POETIC: [
            "A shadow fell upon {context}, but light shall soon restore its grace.",
            "The harmony of {context} was briefly lost, but the melody returns.",
            "Clouds gathered over {context}, but they drift away, leaving clarity.",
            "A stumble on the path of {context}, but we rise and walk on.",
            "The thread of {context} tangled, but patience unravels the knot.",
            "Silence fell where {context} should have sung, but the voice returns.",
            "Like a cracked vase, {context} was flawed, but gold now fills the cracks.",
            "Winter came for {context}, but spring is already here.",
        ],
        Style.GROVELING: [
            "I am terribly sorry about {context}. I promise to do better next time.",
            "I feel awful that I let {context} slip. It won't happen again, I swear.",
            "I know I messed up {context} a little bit. Please accept my sincerest, most humble apology.",
            "I am kicking myself over {context}. I am so, so sorry.",
            "Please don't be disappointed in me regarding {context}. I'll make it up to you.",
            "I can't believe I let {context} happen. I am ashamed.",
            "I offer my humblest apologies for the {context} situation. I am wretched.",
            "Please find it in your heart to overlook my blunder with {context}.",
        ],
        Style.HAIKU: [
            "Code broke in the night,\n{context} wept silently,\nI have healed it now.",
            "Blue screen in my mind,\n{context} suffered for a bit,\nGreen lights shine again.",
            "Mistake was made here,\n{context} stumbled and then fell,\nUp it gets again.",
            "Testing in prod sucks,\n{context} paid the price for it,\nNever again, swear.",
            "Clouds block the warm sun,\n{context} is cold and afraid,\nI bring blankets now.",
            "Oops, I broke the thing,\n{context} is the thing I broke,\nNow I fix the thing.",
            "Logic went astray,\n{context} followed into dark,\nBack to light we go.",
            "Sigh, a bug appeared,\n{context} was the victim here,\nPatch is on the way.",
        ],
        Style.LEGAL_DISCLAIMER: [
            "Without admission of liability, we note that {context} experienced a non-conforming event which has since been remediated.",
            "Pursuant to applicable policies, {context} was subject to an unscheduled corrective action. No further disclosure is required.",
            "We hereby acknowledge that {context} did not perform within nominal parameters. Remediation is complete.",
            "Reserving all rights and defenses, we confirm that {context} has been restored to specification.",
            "This statement regarding {context} is made for informational purposes only and shall not constitute an admission.",
            "An issue affecting {context} has been resolved in accordance with Section 4.1 of our terms of service.",
            "We disclaim any warranty regarding the prior state of {context}; the current state is as represented.",
            "Notice is hereby given that {context} has been brought into compliance.",
        ],
        Style.CORPORATE_DOUBLESPEAK: [
            "Mistakes were made in the context of {context}. Learnings have been captured and synergized across the org.",
            "{context} encountered a non-standard outcome. We have unblocked it via cross-functional alignment.",
            "We have pivoted on {context} to better serve our strategic imperatives.",
            "An action item against {context} has been closed out per our retro cadence.",
            "We are leveraging the {context} learnings to inform our forward-looking roadmap.",
            "A friction point in {context} has been de-risked and operationalized.",
            "{context} has been right-sized following stakeholder alignment.",
            "We have actioned the necessary deltas on {context} to drive sustained value creation.",
        ],
        Style.SHAKESPEAREAN: [
            "Alas, mine hand did slip upon {context}, but 'tis now restor'd by mine own labor.",
            "O fie upon mine carelessness! Yet {context} is mended, and the day is sav'd.",
            "Mine apologies, good gentles, for the foul turn of {context}; the wound is dress'd.",
            "Verily, {context} did suffer a brief calamity, but courage hath set it aright.",
            "Pray pardon me, for I have wrong'd {context}; the deed is undone with haste.",
            "A pox upon mine inattention to {context}! Yet the matter is settled.",
            "Mine heart is heavy for the trouble at {context}, but lo, the storm hath passed.",
            "Forgive, I pray thee, the small calamity of {context}; harmony reigns once more.",
        ],
        Style.PIRATE: [
            "Yarr, {context} took on a bit o' water, but we be bailing it out, ye landlubbers.",
            "Avast! {context} hit a wave broadside. Course corrected, full sails ahead!",
            "Arrr, {context} gave us a fright, but the crew be patching her up smartly.",
            "Shiver me timbers, {context} sprung a leak. Caulked her up with rum and grit.",
            "A squall caught {context} off guard, matey, but we've weathered worse than this.",
            "Blow me down, {context} took a hit, but we be sailing true again.",
            "Sorry 'bout the trouble with {context}, ye scurvy dogs. The deck's swabbed now.",
            "Arr, {context} hit a reef, but the hull holds. Onwards to the next bay!",
        ],
    },
    Severity.MAJOR: {
        Style.PROFESSIONAL: [
            "We regret the significant issue affecting {context}. A full root cause analysis is underway, and we are committed to preventing recurrence.",
            "Please accept our formal apology for the disruption caused by {context}. We are prioritizing this issue at the highest level.",
            "The integrity of {context} is paramount to us. We apologize for the recent instability and are implementing robust safeguards.",
            "We understand the gravity of the situation regarding {context} and are deploying all available resources to resolve it.",
            "We sincerely apologize for the operational impact caused by {context}. This does not meet our service standards.",
            "We are treating the {context} incident with the utmost urgency and seriousness.",
            "We regret to inform you of the complications with {context}. We are working tirelessly to restore full functionality.",
            "We take full responsibility for the issues surrounding {context} and are reviewing our internal processes.",
        ],
        Style.CASUAL: [
            "Okay, I really dropped the ball on {context}. I'm working overtime to fix this.",
            "So... about {context}. Not my finest hour. Drinks are on me when this is fixed.",
            "I messed up {context}. Like, actually messed it up. fixing fixing fixing.",
            "Big oof on {context}. I'm sweating right now. Give me a minute.",
            "Yeah, {context} is having a meltdown. And so am I. Working on it.",
            "Look, I'm not gonna lie, {context} is pretty borked. But I'm on it.",
            "Sorry folks, {context} decided to take a dirt nap. Resuscitating now.",
            "I broke {context}. I know, I know. I'm fixing it.",
            "Major facepalm regarding {context}. My bad. Big time.",
        ],
        Style.POETIC: [
            "The storm has broken, and {context} lies in disarray. I shall rebuild what I have torn asunder.",
            "A heavy silence falls where {context} once stood proud. I bear the weight of this ruin.",
            "Fractures run deep in {context}, echoing my own regret.",
            "The pillars of {context} have shaken, and confidence crumbles like dust.",
            "I walked into the darkness of {context} and lost my way.",
            "A wound upon the world is {context}, and I hold the knife.",
            "The stars turned away from {context}, and I was left in the cold.",
            "Shattered glass reflects my failure in {context}.",
        ],
        Style.GROVELING: [
            "Please forgive me! I messed up {context} big time. I am unworthy of your trust but I beg for a second chance.",
            "I am so, so sorry regarding {context}. I will do anything to make it right. Anything.",
            "I am an idiot. A complete fool. {context} is broken because of me. Please don't fire me.",
            "I lay prostrate before you. {context} was my responsibility and I failed.",
            "I don't deserve your kindness after what I did to {context}.",
            "Please, I am begging you, let me fix {context}. I will work for free.",
            "I am garbage. {context} proves it. Please give me one more shot.",
            "I will write 'I am sorry about {context}' on the whiteboard 1000 times.",
        ],
        Style.HAIKU: [
            "System crashing down,\n{context} burns in the dark,\nTears fall on keyboard.",
            "Big mistake today,\n{context} is very broken,\nCoffee is needed.",
            "Loud noises in room,\n{context} is the reason why,\nI want to go home.",
            "Boss is looking mad,\n{context} is the reason why,\nPlease don't fire me.",
            "Red lights flashing bright,\n{context} is in critical,\nDoctor is summoned.",
            "Why did I do that?\n{context} did not deserve this,\nI am full of shame.",
            "Panic in the air,\n{context} gasps for its last breath,\nCPR begins.",
            "Weekend is canceled,\n{context} needs me to survive,\nGoodbye sleep and joy.",
        ],
        Style.LEGAL_DISCLAIMER: [
            "Pursuant to our incident response policy, we acknowledge a significant event affecting {context}. No admission of negligence is hereby implied.",
            "While reserving all rights, we confirm that {context} experienced a material disruption. Counsel has been notified.",
            "We hereby provide notice that {context} did not perform as warranted. A formal incident report shall follow within the required period.",
            "Without prejudice to ongoing analysis, the {context} event is under review by our compliance team.",
            "This communication is made on a strictly without-prejudice basis. The {context} matter remains under investigation.",
            "We disclaim any consequential damages arising from {context} to the maximum extent permitted by law.",
            "Be advised that the {context} incident is the subject of an internal preservation hold.",
            "Per our SLA, the {context} event qualifies as a Tier 2 incident. Service credits, if applicable, will be issued in accordance with Schedule B.",
        ],
        Style.CORPORATE_DOUBLESPEAK: [
            "{context} experienced a non-standard outcome trajectory. We are leveraging this teachable moment to drive transformative change.",
            "The {context} situation is being holistically reviewed through a 360-degree lens.",
            "We are convening a tiger team to drive resolution on {context} and surface key learnings.",
            "{context} has surfaced critical insights that will inform our next-quarter strategic priorities.",
            "We are leaning into the {context} challenge as an opportunity for org-wide alignment.",
            "A blameless post-mortem on {context} has been scheduled to maximize learning velocity.",
            "{context} represents a forcing function for the cultural transformation we have been ideating.",
            "We are taking the {context} feedback under advisement and recalibrating our roadmap accordingly.",
        ],
        Style.SHAKESPEAREAN: [
            "O woe! Mine error in {context} doth weigh heavy upon my soul, and I do beg thy grace.",
            "Alas, the deed is done at {context}, and the consequence falls bitter on mine head.",
            "What hand hath wrought this ruin upon {context}? Mine own, alas, mine own.",
            "Forgive me, noble friend, for the calamity at {context}; mine penance shall be earnest.",
            "The fates have turned against {context} by mine own folly. Mercy, I pray thee, mercy.",
            "Mine shame at {context} is such that I scarce can lift mine eyes.",
            "By all the heavens, I did not mean for {context} to fall so far. Yet fall it did.",
            "Mine sorrow at {context} is a wound that time alone may heal.",
        ],
        Style.PIRATE: [
            "Blimey! {context} be in rough seas, matey. All hands on deck, we be saving her yet!",
            "Arrr, {context} took a cannon to the side. Patching the hull as we speak, ye scallywags.",
            "Shiver me timbers, {context} be listing hard to port. The crew's working double watches!",
            "By Davy Jones' beard, {context} hit the rocks. We be salvaging what we can.",
            "Yarr, I steered {context} into the storm. The Captain'll have me hide for this one.",
            "Avast! {context} took on water something fierce. Bail, ye dogs, bail!",
            "Arrr, the {context} mast came down. We be rigging a new one with whatever we got.",
            "Sorry 'bout {context}, ye scurvy dogs. I'll be in the brig if ye need me.",
        ],
    },
    Severity.CRITICAL: {
        Style.PROFESSIONAL: [
            "We formally apologize for the critical failure regarding {context}. This falls below our standards. We are taking immediate corrective action and will provide a detailed incident report.",
            "The outage affecting {context} is unacceptable. We accept full responsibility and are dedicating all resources to restoration.",
            "We deeply regret the impact of the {context} failure on your operations. We are currently executing our disaster recovery protocols.",
            "We are aware of the critical situation with {context} and have mobilized our emergency response team.",
            "We apologize unreservedly for the downtime of {context}. This is a top-priority incident.",
            "Failure of {context} is not an option, yet it occurred. We are conducting a forensic analysis.",
            "We understand that {context} is vital to your business. We are working around the clock to restore it.",
            "We sincerely apologize for the severe disruption caused by the failure of {context}.",
        ],
        Style.CASUAL: [
            "Yikes. {context} is on fire. I am putting it out as we speak. Really sorry about this.",
            "Okay, everyone panic... wait, no, don't panic. {context} is down. I am panicking enough for everyone.",
            "So, {context} is basically toast right now. I'm scraping off the burnt parts. Bear with me.",
            "Everything is fine. {context} is fine. I am fine. (It is not fine). Sorry.",
            "Holy smokes, {context} just exploded. I'm bringing the fire extinguisher.",
            "This is not a drill. {context} is down. I repeat, {context} is down.",
            "I'm not gonna sugarcoat it. {context} is in bad shape. Sorry!",
            "If you need me, I'll be in the server room crying over {context}.",
            "Yeah... {context} is kaput. Working on a miracle.",
        ],
        Style.POETIC: [
            "The foundations shake, the walls of {context} crumble. My heart is heavy with the weight of this disaster.",
            "In the ruins of {context}, I stand alone, seeking redemption in the ashes.",
            "The sun has set upon {context}, and a long dark night begins.",
            "A chasm has opened beneath {context}, swallowing our hopes.",
            "The song of {context} has turned to a funeral dirge.",
            "I carry the burden of {context}'s fall upon my weary shoulders.",
            "The sky weeps for {context}, and I weep with it.",
            "Desolation reigns where {context} once thrived.",
        ],
        Style.GROVELING: [
            "I am on my knees. {context} is a disaster and it is my fault. Do with me what you will, but please spare the others.",
            "There are no words for how sorry I am about {context}. I have failed you. I have failed everyone.",
            "Please, I beg of you, have mercy. {context} went wrong and I take full blame. Just tell me what to do.",
            "I am not worthy of eye contact. {context} is a catastrophe. I am wretched.",
            "I will accept any punishment for the {context} disaster. Just name it.",
            "I am scum. I am slime. I broke {context}. Please don't kill me.",
            "I will wash your car for a year if you forgive me for {context}.",
            "My life is over. {context} is ruined. Please have pity on my soul.",
        ],
        Style.HAIKU: [
            "Chaos reigns supreme,\n{context} is lost to the void,\nWhy did I push main?",
            "Servers are melting,\n{context} screams in agony,\nUpdate resume.",
            "All hope is lost now,\n{context} has abandoned us,\nDarkness is my friend.",
            "Phone is blowing up,\n{context} is the reason why,\nI will fake my death.",
            "Sirens in distance,\n{context} caused the alarm bells,\nI am very scared.",
            "Code is spaghetti,\n{context} is the meatball now,\nDinner is ruined.",
            "Resume is ready,\n{context} was my final act,\nGoodbye cruel world.",
            "Help me Obi-Wan,\n{context} is our only hope,\nBut he is not here.",
        ],
        Style.LEGAL_DISCLAIMER: [
            "While reserving all rights and defenses, we note that {context} experienced an unscheduled total disruption. This communication does not constitute an admission against interest.",
            "Counsel has been engaged regarding the {context} event. All further inquiries should be directed to our legal department.",
            "A litigation hold has been issued in connection with {context}. All relevant records are preserved.",
            "We acknowledge a Tier 1 service event affecting {context}, subject to the limitations of liability set forth in the master agreement.",
            "Per regulatory obligations, the {context} incident has been disclosed to the relevant authorities.",
            "We deny any allegation of gross negligence regarding {context}, while continuing to investigate root cause.",
            "The {context} event is the subject of an active internal investigation. No further comment will be provided at this time.",
            "Without waiving any defenses, we confirm receipt of your inquiry regarding {context}. A formal response will follow.",
        ],
        Style.CORPORATE_DOUBLESPEAK: [
            "The {context} event represents a unique opportunity for paradigm-level course correction. We are reimagining the path forward.",
            "We are convening an executive war room to drive resolution on {context} with the appropriate level of urgency.",
            "{context} has surfaced an opportunity to fundamentally re-architect our approach to operational excellence.",
            "Out of an abundance of caution, we have escalated {context} to the steering committee for holistic review.",
            "We are deploying our crisis playbook on {context} with full alignment from senior leadership.",
            "{context} has prompted a strategic pause to ensure we are operating with the highest fidelity to our values.",
            "We are taking the {context} feedback seriously and engaging external advisors to validate our response.",
            "A blameless after-action review on {context} is scheduled, with key learnings to be socialized broadly.",
        ],
        Style.SHAKESPEAREAN: [
            "By heavens above, {context} is undone! What tragic deed have mine own hands wrought!",
            "O bitter fortune! {context} lies in ruin, and the blame falls squarely upon mine brow.",
            "Mine grief at {context} is such that words themselves do fail me.",
            "What darkness hath descended upon {context}? 'Tis a night with no dawn in sight.",
            "Cursed be the hour I touched {context}! Now ruin and ash are all that remain.",
            "Mine soul doth bleed for {context}, and no balm on earth shall soothe it.",
            "O most miserable hour! {context} hath fallen, and with it mine standing.",
            "Forgive me, sweet patron, for the catastrophe at {context}; I am undone.",
        ],
        Style.PIRATE: [
            "Shiver me timbers, {context} be sinking fast! Abandon ship? Nay, not yet, ye dogs!",
            "Arrr, the {context} hull's been split clean through! Bail with yer hats if ye must!",
            "By Blackbeard's cursed soul, {context} took a broadside and she be going down!",
            "Yarr, I steered {context} straight into a hurricane. The Kraken hath claimed her.",
            "All hands! {context} be ablaze from stem to stern! Save what ye can, lads!",
            "Avast! {context} struck the reef at full sail. The Captain will keelhaul me for sure.",
            "Blimey, {context} be lost to the deep. Davy Jones hath a new prize this day.",
            "Sorry, mateys, I sailed {context} straight to her doom. The plank awaits.",
        ],
    },
    Severity.NUCLEAR: {
        Style.PROFESSIONAL: [
            "We unreservedly apologize for the catastrophic failure of {context}. Legal and compliance teams have been notified. We accept full responsibility for the consequences.",
            "There is no excuse for the total loss of {context}. We are cooperating fully with authorities and regulatory bodies.",
            "We are ceasing operations related to {context} effective immediately. We deeply regret the irreversible damage caused.",
            "This is a statement regarding the total collapse of {context}. We are profoundly sorry.",
            "We advise all stakeholders of {context} to take immediate protective measures. We have failed.",
            "We are currently drafting a formal public apology regarding the {context} catastrophe.",
            "We understand that apologies are insufficient for the loss of {context}. We await the lawsuits.",
            "The destruction of {context} is a tragedy of our own making. We accept our fate.",
        ],
        Style.CASUAL: [
            "So... {context} is gone. Like, gone gone. I might need a new identity. Sorry?",
            "If anyone asks, I was never here and I don't know what {context} is. (Just kidding... sort of. Sorry.)",
            "I think I just broke the internet with {context}. I'm gonna go live in a cave now. Bye.",
            "Remember {context}? Yeah, me neither. Let's never speak of this again.",
            "Pack your bags. {context} happened. We need to leave the country.",
            "So, funny story... {context} essentially evaporated. My bad?",
            "I pushed the big red button on {context}. I shouldn't have done that.",
            "Welp. {context} is history. It was nice knowing you all.",
            "I would say I'm sorry about {context}, but I don't think that covers it.",
        ],
        Style.POETIC: [
            "The world ends not with a whimper, but with my mistake in {context}. All is lost. Farewell.",
            "I have gazed into the abyss of {context}, and the abyss gazed back, weeping.",
            "Let my name be erased from history, for I have destroyed {context}.",
            "The stars are extinguished, and {context} is but a memory in the void.",
            "Silence is the only appropriate response to the death of {context}.",
            "I am the destroyer of worlds, specifically {context}.",
            "Ashes to ashes, dust to dust, {context} is gone, and so is my trust.",
            "The tapestry of time is unraveled by my hand at {context}.",
        ],
        Style.GROVELING: [
            "I offer my resignation and my firstborn child. {context} is destroyed. There is no forgiveness for what I have done.",
            "I am willing to go to prison for {context}. Just please, stop looking at me with those eyes.",
            "I am the architect of my own destruction. {context} is gone. I am nothing. I am sorry.",
            "Please just end my misery. I can't live knowing I did this to {context}.",
            "I will surrender all my earthly possessions to atone for {context}.",
            "There is no hell deep enough for what I did to {context}.",
            "I am a monster. I destroyed {context}. Run away from me.",
            "Please spit on me. I deserve it for {context}.",
        ],
        Style.HAIKU: [
            "Game over man, game over,\n{context} is dust and echo,\nFired I shall be.",
            "Delete production,\n{context} vanished in thin air,\nCareer is finished.",
            "Apocalypse now,\n{context} is the ground zero,\nRun for the hills boys.",
            "No backup exists,\n{context} is gone forever,\nWhy was I born?",
            "Lawyers are calling,\n{context} is the legal case,\nI go to jail now.",
            "Total meltdown here,\n{context} is radioactive,\nDo not come closer.",
            "Legend of failure,\n{context} will be my legacy,\nSadness is my life.",
            "Empty desk remains,\n{context} was the final straw,\nUser has left chat.",
        ],
        Style.LEGAL_DISCLAIMER: [
            "This statement is made without prejudice and on a strictly privileged basis. Counsel has advised against further commentary regarding {context}.",
            "All inquiries concerning {context} must be directed to our outside counsel. No employee is authorized to discuss this matter.",
            "Pursuant to a litigation hold, all records relating to {context} are being preserved. We decline to comment further.",
            "We hereby invoke all applicable contractual limitations of liability in connection with {context}.",
            "The {context} matter is the subject of pending regulatory proceedings. We will respond through the appropriate channels.",
            "Without waiving any privilege, attorney-client communications regarding {context} are not subject to disclosure.",
            "We are exercising our right to remain silent on the specifics of {context}. This is not an admission.",
            "Affected parties should consult their own legal counsel regarding any rights arising from {context}. We make no representation as to remedies available.",
        ],
        Style.CORPORATE_DOUBLESPEAK: [
            "We are sunsetting {context} as part of a strategic realignment. Affected stakeholders will receive a forward-looking roadmap shortly.",
            "{context} has been deprioritized in service of our refreshed strategic focus. We thank our partners for their patience.",
            "We are winding down {context} to better align with our north-star outcomes and free up capacity for high-leverage initiatives.",
            "Following a holistic review, {context} has been identified as a non-strategic asset. We are exploring divestiture options.",
            "{context} has transitioned to end-of-life status. A migration playbook will be socialized in due course.",
            "We are reimagining our portfolio, and {context} will not be part of the go-forward strategy.",
            "Out of an abundance of caution, all {context} operations are paused pending a comprehensive strategic review.",
            "{context} represents a pre-pivot legacy that we are gracefully retiring as we lean into our next chapter.",
        ],
        Style.SHAKESPEAREAN: [
            "Et tu, {context}? Then fall, mine career. The rest is silence.",
            "Out, out, brief candle! {context} is no more, and I am but a walking shadow.",
            "Mine kingdom for a backup! Yet none exists, and {context} is lost to time.",
            "O cursed spite, that ever I was born to set {context} right, only to undo it utterly!",
            "Cry havoc, and let slip the dogs of severance! {context} is destroyed, and I with it.",
            "Goodnight, sweet {context}, and flights of angels sing thee to thy rest.",
            "Mine hands shall ne'er be clean. {context} is gone, and so is mine honor.",
            "The fault, dear Brutus, is not in our stars, but in mine commit to {context}.",
        ],
        Style.PIRATE: [
            "Arrr, {context} be at the bottom of Davy Jones' locker. Walk the plank I shall.",
            "Shiver me timbers and curse me bones, {context} be gone forever to the deep blue.",
            "Yarr, I sank {context} with all hands aboard. The Kraken sends its regards.",
            "Blimey, {context} be naught but driftwood now. Hand me the rum, I be done for.",
            "By Blackbeard's ghost, I scuttled {context} myself. The mutiny be well-earned.",
            "All hands lost, {context} swallowed whole. I'll be marooned for this one, mateys.",
            "Arrr, {context} sailed off the edge of the world. There be no map back from here.",
            "Sorry, ye scurvy crew. {context} be a ghost ship now, and I be its lonely captain.",
        ],
    },
}
